version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/pac-man-game
    steps:
      - checkout
      - restore_cache:
          key: pac-man-game-1.0-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pac-man-game-1.0-{{ checksum "pom.xml" }}
      - run: mvn compile
      - run: mvn build
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/pac-man-game-1.0.jar

